export BASH_SILENCE_DEPRECATION_WARNING=1
PS1="\e[100m\e[92m\e[1mMinishell-42\e[49m\e[0m \e[4m\d \t\e[0m $> "

printf "                                        \n"
printf "               ▄█████████▄              \n"
printf "            ▄███████████████▄           \n"
printf "         ██████▀   ██   ▀███████        \n"
printf "      ███   ▀███   ██   ███▀   ███      \n"
printf "     ██████   ██   ██   ██   ██████     \n"
printf "     ██   ██   ██  ██  ██   ██   ██     \n"
printf "    ███    ██  ██  ██  ██  ██    ███    \n"
printf "    ██ ██   ██  █  ██  █  ██   ██ ██    \n"
printf "    ██  ███  ██ ██ ██ ██ ██  ███  ██    \n"
printf "    ██    ██  ██ █ ██ █ ██  ██    ██    \n"
printf "    ████▄   ██ █  █  █  █ ██   ▄████    \n"
printf "       ████   █          █   ████       \n"
printf "          ██                ██          \n"
printf "          ████████▄  ▄████████          \n"
printf "                  ▀██▀                  \n"
printf "           _       _     _          _ _ \n"
printf " _ __ ___ (_)_ __ (_)___| |__   ___| | |\n"
printf "|  _   _ \\| |  _ \\| / __|  _ \\ / _ \\ | |\n"
printf "| | | | | | | | | | \\__ \\ | | |  __/ | |\n"
printf "|_| |_| |_|_|_| |_|_|___/_| |_|\\___|_|_|\n\n"

